# Generated by Django 4.0.5 on 2022-06-28 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bolso',
        ),
        migrations.DeleteModel(
            name='pantalon',
        ),
    ]
