# Generated by Django 4.0.5 on 2022-07-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0002_delete_bolso_delete_pantalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campera',
            name='talle',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='casco',
            name='talle',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='guante',
            name='talle',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='guante',
            name='tipo',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
    ]
