# Generated by Django 4.0.5 on 2022-07-13 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiendaapp', '0003_alter_campera_talle_alter_casco_talle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campera',
            name='talle',
            field=models.CharField(max_length=6, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='casco',
            name='talle',
            field=models.CharField(max_length=6, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='guante',
            name='talle',
            field=models.CharField(max_length=6, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
