# Generated by Django 4.0.5 on 2022-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0006_accesorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesorio',
            name='talle',
        ),
        migrations.AlterField(
            model_name='indumentaria',
            name='talle',
            field=models.CharField(max_length=30, verbose_name='Tipo'),
        ),
    ]
