# Generated by Django 4.0.5 on 2022-07-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0010_tecnologia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('Texto', models.CharField(max_length=500, verbose_name='Texto')),
                ('Fecha', models.DateField(verbose_name='Fecha')),
                ('Estado', models.CharField(max_length=50, verbose_name='Estado del evento')),
                ('Valor_de_la_entrada', models.FloatField(verbose_name='Valor de la entrada $')),
                ('Pais', models.CharField(max_length=50, verbose_name=' ')),
                ('Provincia', models.CharField(max_length=50, verbose_name=' Provincia ')),
                ('Localidad', models.CharField(max_length=50, verbose_name=' Localidad ')),
                ('Direccion', models.CharField(max_length=50, verbose_name=' Direccion ')),
                ('Organizador', models.CharField(max_length=50, verbose_name=' Organizador ')),
            ],
        ),
        migrations.AlterField(
            model_name='casco',
            name='talle',
            field=models.CharField(max_length=6, verbose_name='Talle'),
        ),
    ]
