# Generated by Django 4.0.5 on 2022-07-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0011_evento_alter_casco_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='Pais',
            field=models.CharField(max_length=50, verbose_name='Pais '),
        ),
        migrations.AlterField(
            model_name='evento',
            name='Texto',
            field=models.CharField(max_length=5000, verbose_name='Texto'),
        ),
    ]
