# Generated by Django 4.0.5 on 2022-07-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaapp', '0012_alter_evento_pais_alter_evento_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='staticimgen/'),
        ),
    ]
